#!/bin/bash
set -e

apt-get update

# install build dependencies
apt-get install -y gcc make yasm bzip2 \
  libc6-dev libgnutls-dev libogg-dev librtmp-dev libjpeg-dev libpng12-dev \
  libvpx-dev libtheora-dev libxvidcore-dev libmpeg2-4-dev \
  libvorbis-dev libfaad-dev libmp3lame-dev libmpg123-dev libmad0-dev libopus-dev libvo-aacenc-dev

# use all available processor cores for the build
alias make="make -j$(awk '/^processor/ { N++} END { print N }' /proc/cpuinfo)"

# compile x264
mkdir -p /tmp/x264
wget "http://git.videolan.org/?p=x264.git;a=snapshot;h=HEAD;sf=tgz" -O - | tar -zxf - -C /tmp/x264 --strip=1
cd /tmp/x264 && ./configure --prefix=/usr --enable-shared --disable-opencl
make && make install

# compile ffmpeg
mkdir -p /tmp/ffmpeg/
wget "http://git.videolan.org/?p=ffmpeg.git;a=snapshot;h=HEAD;sf=tgz" -O - | tar zxf - --strip=1 -C /tmp/ffmpeg/
cd /tmp/ffmpeg/
./configure --prefix=/usr --disable-static --enable-shared --enable-gpl --enable-nonfree \
  --enable-libx264 --enable-libmp3lame --enable-libvpx --enable-librtmp --enable-yasm \
  --enable-ffmpeg --enable-ffplay --enable-ffserver --enable-network --enable-gnutls \
  --enable-libopus --disable-debug --enable-libvo-aacenc --enable-version3
make && make install

# purge build dependencies, don't need 'em anymore
apt-get purge -y --auto-remove gcc make yasm bzip2 \
  libc6-dev libgnutls-dev libogg-dev librtmp-dev libjpeg-dev libpng12-dev \
  libvpx-dev libtheora-dev libxvidcore-dev libmpeg2-4-dev \
  libvorbis-dev libfaad-dev libmp3lame-dev libmpg123-dev libmad0-dev libopus-dev libvo-aacenc-dev

# cleanup
rm -rf /tmp/x264
rm -rf /tmp/ffmpeg
rm -rf /var/lib/apt/lists/*
